apiVersion: v1
kind: ConfigMap
metadata:
  name: mikrotik-exporter
  namespace: default
data:
  mktxp.conf: |
    [Home-Router]
    enabled = True         # turns metrics collection for this RouterOS device on / off

    hostname = MIKROTIK_HOSTNAME    # RouterOS IP address
    port = 8728             # RouterOS API / API-SSL service port

    username = environ     # RouterOS user, needs to have 'read' and 'api' permissions
    password = environ

    use_ssl = False                 # enables connection via API-SSL servis
    no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
    ssl_certificate_verify = False  # turns SSL certificate verification on / off

    installed_packages = True       # Installed packages
    dhcp = True                     # DHCP general metrics
    dhcp_lease = True               # DHCP lease metrics

    connections = True              # IP connections metrics
    connection_stats = False        # Open IP connections metrics

    pool = True                     # Pool metrics
    interface = True                # Interfaces traffic metrics

    firewall = True                 # IPv4 Firewall rules traffic metrics
    ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
    ipv6_neighbor = False           # Reachable IPv6 Neighbors

    poe = True                      # POE metrics
    monitor = True                  # Interface monitor metrics
    netwatch = True                 # Netwatch metrics
    public_ip = True                # Public IP metrics
    route = True                    # Routes metrics
    wireless = True                 # WLAN general metrics
    wireless_clients = True         # WLAN clients metrics
    capsman = True                  # CAPsMAN general metrics
    capsman_clients = True          # CAPsMAN clients metrics

    user = True                     # Active Users metrics
    queue = True                    # Queues metrics

    remote_dhcp_entry = None        # An MKTXP entry for remote DHCP info resolution (capsman/wireless)

    use_comments_over_names = True  # when available, forces using comments over the interfaces names
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikrotik-exporter
  template:
    metadata:
      labels:
        app: mikrotik-exporter
    spec:
      containers:
        - name: mikrotik-exporter
          image: krab55/mktxp:latest
          volumeMounts:
            - name: config
              mountPath: /home/mktxp/mktxp-cm
          ports:
            - containerPort: 49090
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mikrotik
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mikrotik
                  key: password
      volumes:
        - name: config
          configMap:
            name: mikrotik-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter
spec:
  selector:
    app: mikrotik-exporter
  ports:
    - name: http
      protocol: TCP
      port: 49090
      targetPort: 49090
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mikrotik
type: Opaque
data:
  username: MIKROTIK_USERNAME
  password: MIKROTIK_PASSWORD
