---
name: Docker Build

on:
  push:
    branches: ["main"]
    # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "kubernetes/**"
  pull_request:
    branches:
      ["main"]
      # don't rebuild image if someone only edited unrelated files
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "kubernetes/**"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/mktxp:$(date +%s) --tag ${{ secrets.DOCKERHUB_USERNAME }}/mktxp:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/mktxp --all-tags
